# this script is to store the variables which will be used across the project, in order to avoid typos.

""" --- Assignment 1 constants --- """
titleType_name = "titleType"
isAdult_name = "isAdult"
runtime_name = "runtimeMinutes"
startYear_name = "startYear"
endYear_name = "endYear"
durationYears_name = "durationYears"
nEpisodes_name = "nEpisodes"
averageRating_name = "averageRating"
numVotes_name = "numVotes"
genres_name = "genres"
tconst_name = "tconst"


""" --- Assignment 2 constants --- """
movie_popularity_name = "movie_facebook_likes"
cast_popularity_name = "cast_total_facebook_likes"
nUser_reviews_name = "num_user_for_reviews"
gross_name = "gross"
nCritic_reviews_name = "num_critic_for_reviews"
budget_name = "budget"
cast_pop_1 = "actor_1_facebook_likes"
cast_pop_2 = "actor_2_facebook_likes"
movie_link_name = "movie_imdb_link"